import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// SQL Injection уязвимость
const userId = req.query.id;
const query = "SELECT * FROM users WHERE id = " + userId; // ❌ SQL injection

// XSS уязвимость
const userInput = req.body.content;
return <div dangerouslySetInnerHTML={{ __html: userInput }} />; // ❌ XSS

// Hardcoded credentials
const API_KEY = "sk-1234567890abcdef"; // ❌ Hardcoded secret
const password = "admin123"; // ❌ Hardcoded password

// Command injection
const userPath = req.query.path;
require("child_process").exec("ls " + userPath); // ❌ Command injection
